#include "End_Stat.h"

End_Stat::End_Stat(Point cent)
{
	Center = cent;
	ix = cent.x;
	iy = cent.y;
}

void End_Stat::Draw(Output* pOut) const
{
	pOut->DrawEnd(ix, iy, Selected);
}

void End_Stat::UpdateStatementText()
{
}
bool End_Stat::IsClicked(Point P) const
{	//Check if point P is inside the End statement circle
	int radius = 30;
	int dx = P.x - ix;
	int dy = P.y - iy;
	if (dx * dx + dy * dy <= radius * radius)
		return true;
	else
		return false;
	}
void End_Stat::Save(ofstream& OutFile)
{
	OutFile << "END " << ID << " " << ix << " " << iy << endl;
}
void End_Stat::Load(ifstream& Infile)
{
	Infile >> ID >> ix >> iy;
	Center.x = ix;
	Center.y = iy;
	pInConn = NULL;
}
Point End_Stat::GetInPoint() const
{
	Point In;
	In.x = ix;
	In.y = iy - 30;
	return In;
}
Point End_Stat::GetOutPoint(int branch) const
{
	return Point(-1, -1); // End statement has no outlet
}
Statement* End_Stat::Clone(Point newPoint) const
{
	return new End_Stat(newPoint);
}
void End_Stat::SetConnector(Connector* pConn)
{
	pInConn = NULL;
}
Connector* End_Stat::GetConnector() const
{
	return pInConn;
}
Connector* End_Stat::Simulate(Variable* vars, int& varsize, string& Error)
{
	return pInConn;
}
void End_Stat::Edit(Input* pIn, Output* pOut)
{
	// End statement has no editable parameters
}
void End_Stat::GenerateCode(ofstream& OutFile) {

// no c++ code generated by end statement
}
